Page({
    data:{
        isScrollToLeft:true,
        vip: {
            vipTitle:"VIP会员低至8.5折",
            goldMessage: "会员送双倍金币，可省#52.8#元/月",
            message: null,
            price: "0.02",
            originalPrice: "0.02"
        },
        credit: {
			"title": "储值送会员",
			"label": "充10元送30天会员卡",
			"imgUrl": "http://zlx-img.oss-cn-beijing.aliyuncs.com/new_icon/chuzhi.png",
			"recTitle": "储值送会员"
		},
		"gold": {
			"title": "金币兑好礼",
			"label": "兑会员卡、优惠券",
			"imgUrl": "http://zlx-img.oss-cn-beijing.aliyuncs.com/new_icon/jinbi.png"
        },
        "bannerList": [{
			"type": 2,
			"bannerType": 4,
			"icon": "http://zlx-img.oss-cn-beijing.aliyuncs.com/new_icon/qiandao.png",
			"iconName": "每日签到",
			"url": "http://preapi.zailouxia.com/duiba/freelogin?dbredirect=https%3A%2F%2F63955.activity-1.m.duiba.com.cn%2Fsignactivity%2Findex%3Fid%3D90%26signOptId%3D9179%26dpm%3D63955.41.1.0%26dcm%3D216.90.51.0",
			"num": 0
		}, {
			"type": 1,
			"bannerType": 1,
			"icon": "http://zlx-img.oss-cn-beijing.aliyuncs.com/new_icon/pingjia.png",
			"iconName": "订单评价",
			"url": null,
			"num": 13
		}, {
			"type": 1,
			"bannerType": 2,
			"icon": "http://zlx-img.oss-cn-beijing.aliyuncs.com/new_icon/fankui.png",
			"iconName": "意见反馈",
			"url": null,
			"num": 0
		}, {
			"type": 2,
			"bannerType": 5,
			"icon": "http://zlx-img.oss-cn-beijing.aliyuncs.com/new_icon/zacaidan.png",
			"iconName": "砸彩蛋",
			"url": "http://preapi.zailouxia.com/duiba/freelogin?dbredirect=https%3A%2F%2F63955.activity-1.m.duiba.com.cn%2Fhdtool%2Findex%3Fid%3D3641365%26dbnewopen",
			"num": 0
		}, {
			"type": 1,
			"bannerType": 3,
			"icon": "http://zlx-img.oss-cn-beijing.aliyuncs.com/new_icon/daodian.png",
			"iconName": "到店下单",
			"url": "",
			"num": 0
        },
       ],
       categoryList: [{
        "categoryName": "超值大促",
        "banner": "http://zlx-img.oss-cn-beijing.aliyuncs.com/market/1572191324965_781562.jpg",
        "categoryId": -7,
        "goodsList": [{
            "goodsId": 123883,
            "goodsLongName": "伊藤园茉莉白茶无糖500ml",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1567997215478_945789.jpg?x-oss-process=style/goods600",
            "sort": 1800,
            "marketPrice": "5.00",
            "salePrice": "5.00",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 4,
            "promotionDesc": null,
            "specialPrice": {
                "price": "3.50",
                "front": [{
                    "words": "",
                    "tag": "史低价！囤！",
                    "color": "#fac625"
                }],
                "spid": 833,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 3,
            "lastSaleTime": "2019-10-23 18:38:38",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "史低价！囤！",
                "color": "#fac625"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126681,
            "goodsLongName": "老北京橙汁汽水420ml",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1564467358617_901489.jpg?x-oss-process=style/goods600",
            "sort": 1800,
            "marketPrice": "3.00",
            "salePrice": "3.00",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 3,
            "promotionDesc": null,
            "specialPrice": {
                "price": "1.50",
                "front": [{
                    "words": "",
                    "tag": "史低价！囤！",
                    "color": "#fac625"
                }],
                "spid": 833,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 3,
            "lastSaleTime": "2019-07-26 12:39:38",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "史低价！囤！",
                "color": "#fac625"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126800,
            "goodsLongName": "伊利味可滋芝士莓果牛奶饮品240ml",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1569241582510_142511.jpg?x-oss-process=style/goods600",
            "sort": 249,
            "marketPrice": "5.00",
            "salePrice": "5.00",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 5,
            "promotionDesc": null,
            "specialPrice": null,
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": {
                "policies": [{
                    "cut": "1",
                    "cond": "9"
                }],
                "fid": 397,
                "withGlobalCut": true,
                "message": null,
                "conflicts": null,
                "type": 2
            },
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-10-10 00:01:12",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": null,
                "tag": "满9立减",
                "color": "#95cf03"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126803,
            "goodsLongName": "伊利高钙低脂奶250ml",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1569241504994_323993.jpg?x-oss-process=style/goods600",
            "sort": 249,
            "marketPrice": "3.80",
            "salePrice": "3.80",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 2,
            "promotionDesc": null,
            "specialPrice": null,
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": {
                "policies": [{
                    "cut": "1",
                    "cond": "9"
                }],
                "fid": 397,
                "withGlobalCut": true,
                "message": null,
                "conflicts": null,
                "type": 2
            },
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-10-08 13:03:05",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": null,
                "tag": "满9立减",
                "color": "#95cf03"
            }],
            "new": false,
            "inLock": true
        }]
    }, 
    {
        "categoryName": "优惠热销",
        "banner": null,
        "categoryId": -6,
        "goodsList": [{
            "goodsId": 126760,
            "goodsLongName": "伊利畅意100%乳酸菌饮品草莓味330ml",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1570870239018_841722.jpg?x-oss-process=style/goods600",
            "sort": 2199,
            "marketPrice": "5.50",
            "salePrice": "5.50",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 1,
            "promotionDesc": null,
            "specialPrice": {
                "price": "3.85",
                "front": [{
                    "words": "",
                    "tag": "限时7折 不参加满减",
                    "color": "#fac625"
                }],
                "spid": 2,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8,7,6",
                "type": 3,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": true,
                "available": true
            },
            "repSpecialPrice": {
                "price": "3.85",
                "front": [{
                    "words": "",
                    "tag": "限时7折 不参加满减",
                    "color": "#fac625"
                }],
                "spid": 2,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8,7,6",
                "type": 3,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": true,
                "available": true
            },
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 3,
            "lastSaleTime": "2019-09-22 00:01:12",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "限时7折 不参加满减",
                "color": "#fac625"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126759,
            "goodsLongName": "日式杏仁酥小西饼85g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1568981572127_388583.jpg?x-oss-process=style/goods600",
            "sort": 1800,
            "marketPrice": "8.50",
            "salePrice": "8.50",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 4,
            "promotionDesc": null,
            "specialPrice": {
                "price": "5.10",
                "front": [{
                    "words": "",
                    "tag": "史低价！囤！",
                    "color": "#fac625"
                }],
                "spid": 833,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-09-25 14:00:34",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "史低价！囤！",
                "color": "#fac625"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 125206,
            "goodsLongName": "海底捞爽脆牛肚435g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1532917611069_988397.jpg?x-oss-process=style/goods600",
            "sort": 999,
            "marketPrice": "35.90",
            "salePrice": "35.90",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 1,
            "promotionDesc": null,
            "specialPrice": {
                "price": "29.90",
                "front": [{
                    "words": "",
                    "tag": "暖心海底捞 直降6元",
                    "color": "#ff6c57"
                }],
                "spid": 832,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.95",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2018-08-09 10:59:53",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "暖心海底捞 直降6元",
                "color": "#ff6c57"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126737,
            "goodsLongName": "a1蛋黄酥55g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1570871027036_552806.jpg?x-oss-process=style/goods600",
            "sort": 999,
            "marketPrice": "9.90",
            "salePrice": "9.90",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 2,
            "promotionDesc": null,
            "specialPrice": {
                "price": "6.93",
                "front": [{
                    "words": "",
                    "tag": "本周促销",
                    "color": "#ff6c57"
                }],
                "spid": 839,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-10-05 00:01:12",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "本周促销",
                "color": "#ff6c57"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126808,
            "goodsLongName": "唐啵虎白桃乌龙手冲奶茶76g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1569321506551_502067.jpg?x-oss-process=style/goods600",
            "sort": 999,
            "marketPrice": "9.90",
            "salePrice": "9.90",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 5,
            "promotionDesc": null,
            "specialPrice": {
                "price": "8.42",
                "front": [{
                    "words": "",
                    "tag": "新品尝鲜",
                    "color": "#ff6c57"
                }],
                "spid": 837,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 3,
            "lastSaleTime": "2019-10-22 19:07:31",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "新品尝鲜",
                "color": "#ff6c57"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126810,
            "goodsLongName": "唐啵虎茉莉奶绿手冲奶茶76g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1569321617200_829418.jpg?x-oss-process=style/goods600",
            "sort": 999,
            "marketPrice": "9.90",
            "salePrice": "9.90",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 3,
            "promotionDesc": null,
            "specialPrice": {
                "price": "8.42",
                "front": [{
                    "words": "",
                    "tag": "新品尝鲜",
                    "color": "#ff6c57"
                }],
                "spid": 837,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-10-21 00:01:12",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "新品尝鲜",
                "color": "#ff6c57"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126829,
            "goodsLongName": "EDO原味乳酸菌夹心饼干120g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1570760690275_567571.jpg?x-oss-process=style/goods600",
            "sort": 999,
            "marketPrice": "6.50",
            "salePrice": "6.50",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 1,
            "promotionDesc": null,
            "specialPrice": {
                "price": "5.85",
                "front": [{
                    "words": "",
                    "tag": "新品尝鲜",
                    "color": "#ff6c57"
                }],
                "spid": 837,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 1,
            "lastSaleTime": "2019-10-23 18:38:38",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "新品尝鲜",
                "color": "#ff6c57"
            }],
            "new": true,
            "inLock": true
        }, {
            "goodsId": 126830,
            "goodsLongName": "赵州雪梨果肉饮料349ml",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1570760658317_814890.jpg?x-oss-process=style/goods600",
            "sort": 999,
            "marketPrice": "5.50",
            "salePrice": "5.50",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 3,
            "promotionDesc": null,
            "specialPrice": {
                "price": "4.40",
                "front": [{
                    "words": "",
                    "tag": "新品尝鲜",
                    "color": "#ff6c57"
                }],
                "spid": 837,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 1,
            "lastSaleTime": "2019-10-23 18:38:38",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "新品尝鲜",
                "color": "#ff6c57"
            }],
            "new": true,
            "inLock": true
        }, {
            "goodsId": 126847,
            "goodsLongName": "旺旺经典原味煎饼100g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1571135750925_368896.jpg?x-oss-process=style/goods600",
            "sort": 999,
            "marketPrice": "8.00",
            "salePrice": "8.00",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 2,
            "promotionDesc": null,
            "specialPrice": {
                "price": "6.40",
                "front": [{
                    "words": "",
                    "tag": "新品尝鲜",
                    "color": "#ff6c57"
                }],
                "spid": 837,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 1,
            "lastSaleTime": "2019-10-23 18:38:38",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "新品尝鲜",
                "color": "#ff6c57"
            }],
            "new": true,
            "inLock": true
        }, {
            "goodsId": 126850,
            "goodsLongName": "白家阿宽四川甜水面270g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1571135583334_955838.jpg?x-oss-process=style/goods600",
            "sort": 999,
            "marketPrice": "14.50",
            "salePrice": "14.50",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 1,
            "promotionDesc": null,
            "specialPrice": {
                "price": "12.90",
                "front": [{
                    "words": "",
                    "tag": "新品尝鲜",
                    "color": "#ff6c57"
                }],
                "spid": 837,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 1,
            "lastSaleTime": "2019-10-23 10:21:00",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "新品尝鲜",
                "color": "#ff6c57"
            }],
            "new": true,
            "inLock": true
        }, {
            "goodsId": 125740,
            "goodsLongName": "吉利火星焦糖口味爆米花108g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1537239880827_308954.jpg?x-oss-process=style/goods600",
            "sort": 998,
            "marketPrice": "10.80",
            "salePrice": "10.80",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 3,
            "promotionDesc": null,
            "specialPrice": {
                "price": "9.18",
                "front": [{
                    "words": "",
                    "tag": "新品尝鲜",
                    "color": "#ff6c57"
                }],
                "spid": 837,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-10-23 18:38:38",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "新品尝鲜",
                "color": "#ff6c57"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126068,
            "goodsLongName": "吉利火星奶油口味爆米花108g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1542693382769_41471.jpg?x-oss-process=style/goods600",
            "sort": 998,
            "marketPrice": "10.80",
            "salePrice": "10.80",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 2,
            "promotionDesc": null,
            "specialPrice": {
                "price": "8.64",
                "front": [{
                    "words": "",
                    "tag": "新品尝鲜",
                    "color": "#ff6c57"
                }],
                "spid": 837,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-10-23 18:38:38",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "新品尝鲜",
                "color": "#ff6c57"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 123870,
            "goodsLongName": "香飘飘原味奶茶80g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1571368013061_341100.jpg?x-oss-process=style/goods600",
            "sort": 930,
            "marketPrice": "4.50",
            "salePrice": "4.50",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 2,
            "promotionDesc": null,
            "specialPrice": {
                "price": "4.05",
                "front": [{
                    "words": "",
                    "tag": "新品尝鲜",
                    "color": "#ff6c57"
                }],
                "spid": 837,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-10-23 18:38:38",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "新品尝鲜",
                "color": "#ff6c57"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 124157,
            "goodsLongName": "香飘飘奶茶红豆味64g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1541647049326_128580.jpg?x-oss-process=style/goods600",
            "sort": 900,
            "marketPrice": "6.00",
            "salePrice": "6.00",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 4,
            "promotionDesc": null,
            "specialPrice": {
                "price": "5.40",
                "front": [{
                    "words": "",
                    "tag": "新品尝鲜",
                    "color": "#ff6c57"
                }],
                "spid": 837,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 1,
            "lastSaleTime": "2019-10-22 19:07:31",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "新品尝鲜",
                "color": "#ff6c57"
            }],
            "new": true,
            "inLock": true
        }, {
            "goodsId": 126693,
            "goodsLongName": " 蒙牛冠益乳草莓味250g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1564050073365_828626.jpg?x-oss-process=style/goods600",
            "sort": 852,
            "marketPrice": "7.50",
            "salePrice": "7.50",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 1,
            "promotionDesc": null,
            "specialPrice": null,
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": {
                "policies": [{
                    "cut": "5.1",
                    "cond": "8"
                }],
                "fid": 386,
                "withGlobalCut": true,
                "message": null,
                "conflicts": null,
                "type": 2
            },
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 1,
            "lastSaleTime": "2019-10-23 00:01:13",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": null,
                "tag": "两件9.9元",
                "color": "#fb8834"
            }],
            "new": true,
            "inLock": true
        }, {
            "goodsId": 126485,
            "goodsLongName": "元気森林白桃味苏打气泡水480ml",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1567997274940_181644.jpg?x-oss-process=style/goods600",
            "sort": 850,
            "marketPrice": "5.00",
            "salePrice": "5.00",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 10,
            "promotionDesc": null,
            "specialPrice": null,
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": {
                "policies": [{
                    "cut": "2.5",
                    "cond": "6"
                }],
                "fid": 388,
                "withGlobalCut": true,
                "message": null,
                "conflicts": null,
                "type": 2
            },
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-04-18 13:22:51",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": null,
                "tag": "第二件半价",
                "color": "#fb8834"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126763,
            "goodsLongName": "元気森林青瓜味苏打气泡水480ml",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1569468949501_37373.jpg?x-oss-process=style/goods600",
            "sort": 850,
            "marketPrice": "5.00",
            "salePrice": "5.00",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 3,
            "promotionDesc": null,
            "specialPrice": null,
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": {
                "policies": [{
                    "cut": "5",
                    "cond": "6"
                }],
                "fid": 378,
                "withGlobalCut": true,
                "message": null,
                "conflicts": null,
                "type": 2
            },
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-09-08 00:01:12",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": null,
                "tag": "第二件0元",
                "color": "#fb8834"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126791,
            "goodsLongName": "纤禧之恋石榴轻莓味饮料500ml",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1568982136376_627058.jpg?x-oss-process=style/goods600",
            "sort": 849,
            "marketPrice": "4.50",
            "salePrice": "4.50",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 5,
            "promotionDesc": null,
            "specialPrice": null,
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": {
                "policies": [{
                    "cut": "3.5",
                    "cond": "5"
                }],
                "fid": 366,
                "withGlobalCut": true,
                "message": null,
                "conflicts": null,
                "type": 2
            },
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 3,
            "lastSaleTime": "2019-10-08 13:03:05",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": null,
                "tag": "第二件1元",
                "color": "#fb8834"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126868,
            "goodsLongName": "百事一口阳光甜虾味海苔糙米脆18g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1571368100700_134825.jpg?x-oss-process=style/goods600",
            "sort": 849,
            "marketPrice": "9.90",
            "salePrice": "9.90",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 5,
            "promotionDesc": null,
            "specialPrice": null,
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": {
                "policies": [{
                    "cut": "8.9",
                    "cond": "10"
                }],
                "fid": 387,
                "withGlobalCut": true,
                "message": null,
                "conflicts": null,
                "type": 2
            },
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 1,
            "lastSaleTime": "2019-10-23 18:38:38",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": null,
                "tag": "第二件1元",
                "color": "#fb8834"
            }],
            "new": true,
            "inLock": true
        }, {
            "goodsId": 125385,
            "goodsLongName": "可口怡泉+C柠檬味汽水400ml",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1569468333935_58837.jpg?x-oss-process=style/goods600",
            "sort": 750,
            "marketPrice": "4.50",
            "salePrice": "4.50",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 5,
            "promotionDesc": null,
            "specialPrice": null,
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": {
                "policies": [{
                    "cut": "2.25",
                    "cond": "5"
                }],
                "fid": 389,
                "withGlobalCut": true,
                "message": null,
                "conflicts": null,
                "type": 2
            },
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-08-02 00:01:12",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": null,
                "tag": "第二件半价",
                "color": "#fb8834"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 124587,
            "goodsLongName": "福成老北京风味发酵乳200g",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1530694700695_797594.jpg?x-oss-process=style/goods600",
            "sort": 399,
            "marketPrice": "6.50",
            "salePrice": "6.50",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 3,
            "promotionDesc": null,
            "specialPrice": {
                "price": "6.50",
                "front": [{
                    "words": "",
                    "tag": "会员日特价",
                    "color": "#ff6c57"
                }],
                "spid": 674,
                "maxBuyNum": 0,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": null,
                "vipOnlyFlag": false,
                "conflicts": "",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": true,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.75",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-10-20 00:01:13",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "会员日特价",
                "color": "#ff6c57"
            }],
            "new": false,
            "inLock": true
        }, {
            "goodsId": 126756,
            "goodsLongName": "康师傅鲜果橙果汁饮料310ml",
            "goodsPic": "http://zlx-img.oss-cn-beijing.aliyuncs.com/goods/1569468708499_291954.jpg?x-oss-process=style/goods600",
            "sort": 399,
            "marketPrice": "2.50",
            "salePrice": "2.50",
            "finalPrice": null,
            "recMessage": null,
            "availableNum": 10,
            "promotionDesc": null,
            "specialPrice": {
                "price": "1.99",
                "front": [{
                    "words": "",
                    "tag": "超值低价",
                    "color": "#fac625"
                }],
                "spid": 744,
                "maxBuyNum": 1,
                "avaDayNum": 0,
                "dayNumReached": 0,
                "text": "该商品可特价购买1件，超出后按原价购买哦~",
                "vipOnlyFlag": false,
                "conflicts": "8",
                "type": null,
                "userType": 0,
                "priceFlag": 1,
                "compatFlag": false,
                "replacement": false,
                "available": true
            },
            "repSpecialPrice": null,
            "expSpecialPrice": null,
            "discountRuler": null,
            "avaDayNum": 0,
            "fullcuts": null,
            "vipDisCount": "0.90",
            "cargoStatus": 1,
            "tag": 2,
            "lastSaleTime": "2019-09-02 00:01:11",
            "vipLabel": null,
            "vipOnlyFlag": false,
            "front": [{
                "words": "",
                "tag": "超值低价",
                "color": "#fac625"
            }],
            "new": false,
            "inLock": true
        }]
    }]

    },
    bindscrolltoupper(){
        let me=this;
        
        !me.data.isScrollToLeft?me.setData({"isScrollToLeft":true}):'';
    },
    bindscrolltolower(){
        let me=this;
        me.data.isScrollToLeft?me.setData({"isScrollToLeft":false}):'';
    }
})